const lang = {
  en: {
    aiSearchPlaceholder: "What are you thinking...?",
    accountBackButton: "Back to Ai-Flix.",
    overView: "Overview",
    membership: "Membership",
    security: "Security",
    settings: "Settings",
    chooseLanguage: "Choose Language",
    account: "Account",
    membershipDetails: "Membership details",
    planDetails: "Plan Details",
    accountDetails: "Account Details",
    helpCenter: "Help Center",
    signOut: "Sign out of Ai-Flix",
    nowPlaying: "Now Playing",
    topRated: "Top Rated",
    popular: "Popular",
    upcoming: "Upcoming",
    play: "Play",
    moreInfo: "More Info",
    heroTitle: "Unlimited movies, shows, and more...",
    heroSubtitle: "Ready to watch? Sign in to continue.",
    enterInfoTo: "Enter your info to",
    signIn: "Sign In",
    signUp: "Sign Up",
    enterYourName: "Enter your Name",
    emailOrPhone: "Email or Phone Number",
    password: "Password",
    newToAiFlix: "New to Ai-Flix? ",
    alreadyHaveAccount: "Already have an account?",
    now: "now.",
  },
  hi: {
    aiSearchPlaceholder: "आप क्या सोच रहे हैं...?",
    accountBackButton: "वापस Ai-Flix पर।",
    overView: "अवलोकन",
    membership: "सदस्यता",
    security: "सुरक्षा",
    settings: "सेटिंग्स",
    chooseLanguage: "भाषा चुनें",
    account: "खाता",
    membershipDetails: "सदस्यता विवरण",
    planDetails: "योजना विवरण",
    accountDetails: "खाता विवरण",
    helpCenter: "सहायता केंद्र",
    signOut: "Ai-Flix से साइन आउट करें",
    nowPlaying: "अभी सिनेमाघरों में",
    topRated: "सर्वश्रेष्ठ रेटिंग वाली फ़िल्में",
    popular: "लोकप्रिय फ़िल्में",
    upcoming: "जल्द आने वाली फ़िल्में",
    play: "प्ले",
    moreInfo: "और जानकारी",
    heroTitle: "अनलिमिटेड फ़िल्में, शो और बहुत कुछ...",
    heroSubtitle: "देखने के लिए तैयार हैं? जारी रखने के लिए साइन इन करें।",
    enterInfoTo: "अपनी जानकारी दर्ज करें",
    signIn: "साइन इन",
    signUp: "साइन अप",
    enterYourName: "अपना नाम दर्ज करें",
    emailOrPhone: "ईमेल या फ़ोन नंबर",
    password: "पासवर्ड",
    newToAiFlix: "Ai-Flix पर नए हैं? ",
    alreadyHaveAccount: "क्या आपका पहले से खाता है? ",
    now: "अब।",
  },
  mr: {
    aiSearchPlaceholder: "तुम्ही काय विचार करत आहात...?",
    accountBackButton: "पुन्हा (Ai-Flix) वळूया.",
    overView: "आढावा",
    membership: "सदस्यत्व",
    security: "सुरक्षा",
    settings: "सेटिंग्ज",
    chooseLanguage: "भाषा निवडा",
    account: "खाते",
    membershipDetails: "सदस्यत्व तपशील",
    planDetails: "योजना तपशील",
    accountDetails: "खाते तपशील",
    helpCenter: "मदत केंद्र",
    signOut: "Ai-Flix मधून साइन आउट करा",
    nowPlaying: "सध्या चित्रपटगृहांमध्ये",
    topRated: "सर्वोच्च रेटिंगचे चित्रपट",
    popular: "लोकप्रिय चित्रपट",
    upcoming: "लवकरच प्रदर्शित होणारे चित्रपट",
    play: "प्ले",
    moreInfo: "अधिक माहिती",
    heroTitle: "अमर्यादित चित्रपट, शो आणि बरेच काही...",
    heroSubtitle: "पाहण्यासाठी तयार आहात? पुढे सुरू ठेवण्यासाठी साइन इन करा.",
    enterInfoTo: "आपली माहिती प्रविष्ट करा",
    signIn: "साइन इन",
    signUp: "साइन अप",
    enterYourName: "आपले नाव प्रविष्ट करा",
    emailOrPhone: "ईमेल किंवा फोन नंबर",
    password: "पासवर्ड",
    newToAiFlix: "Ai-Flix वर नवीन आहात? ",
    alreadyHaveAccount: "तुमचे आधीपासून खाते आहे का? ",
    now: "आता.",
  },
};

export default lang;
